force-app/main/default/objects/Interacao__c/Interacao__c.object-meta.xml
<CustomObject>
    <label>Interacao</label>
    <nameField>
        <label>Interacao Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interacoes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interacao__c/fields/PedidoSuporte__c.field-meta.xml
<CustomField>
    <fullName>PedidoSuporte__c</fullName>
    <label>PedidoSuporte</label>
    <referenceTo>PedidoSuporte__c</referenceTo>
    <relationshipLabel>Interacoes</relationshipLabel>
    <relationshipName>Interacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Agente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PedidoSuporte__c/PedidoSuporte__c.object-meta.xml
<CustomObject>
    <label>PedidoSuporte</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>PedidoSuporte  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PedidosSuporte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selectors/InteracaoSelector.cls
// Repositório para consulta de interações relacionado a determinado pedido
public with sharing class InteracaoSelector implements IInteracaoSelector {

    public List<Interacao__c> getInteracoesAgentePorPedidos(Set<Id> pedidoIds) {
         String Tipo_Agente = 'Agente';

        return [
            // Security para proteger dados de usuários sem acesso aos pedidos
            SELECT Id, Tipo__c, PedidoSuporte__c
            FROM Interacao__c
            WHERE PedidoSuporte__c IN :pedidoIds
            AND Tipo__c = :Tipo_Agente
            WITH SECURITY_ENFORCED
        ];
    }
}